---
title: Blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
name: Chelsea India Supporters' Club
baseurl: https://blog.chelseaindia.com
permalink: "/:year/:month/:day/:title.html"
nav:
- name: Home
  href: https://chelseaindia.com
- name: Twitter
  href: https://twitter.com/ChelseaIndia
sass:
  style: :compressed
