# # # # # # # #
#   Chelsea India Supporters' Club  #
# # # # # # # #

# Basic
name:               "Chelsea India Supporters' Club"

# URL
baseurl:            "https://blog.chelseaindia.com"
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Navigation
nav:
  - name:           "Home"
    href:           "https://chelseaindia.com"
  - name:           "Twitter"
    href:           "https://twitter.com/ChelseaIndia"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
